/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    BacktestContent: typeof import('./components/BacktestContent.vue')['default']
    Deposit: typeof import('./components/Deposit.vue')['default']
    MonitorEditDialog: typeof import('./components/MonitorEditDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StrategyCard: typeof import('./components/StrategyCard.vue')['default']
    StrategyEditDialog: typeof import('./components/StrategyEditDialog.vue')['default']
    TradingViewChart: typeof import('./components/TradingViewChart.vue')['default']
  }
}
